### ISSUE TITLE
Can't install extension in Cursor

### ISSUE THREAD

**Issue by random-yang** [LegoYoda112/nostromo_ui_themes#7]
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/51021a10-81ee-4e33-bf10-2c8734720d40" />

Screenshot meaning: The "thomasgodden.nostromo-ui" extension cannot be installed because it is incompatible with the current version of Cursor (version 0.44.9).

**Comment by random-yang** [comment]
I found a temporary solution: https://www.cursor.com/how-to-install-extension

**Comment by LegoYoda112** [comment]
It looks like there's some versioning issues between vscode and cursor. I already downgraded the minimum required version to 1.93.0, which should be compatible with at least cursor version 0.42 (when they upgraded to vscode version 1.93.1), but looks like that might not be enough to fix.

**Comment by LegoYoda112** [comment]
Ah, looks like your using v0.0.3 of the theme; upgrade to v0.0.4 and it should work. (Just tested with cursor version 0.44.9 on my machine)
